openapi: 3.0.0
info:
  title: Campaign
  description: Campaign API
  version: 1.0.0
paths:
  /campaign/{id}/reward:
    patch:
      summary: 광고 보상 수정
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 광고 아이디
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reward:
                  type: number
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
